version: '3'
services:
  api:
    build:
      context: ../API # Certifique-se de que este caminho está correto para sua API .NET
      dockerfile: Dockerfile
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5198
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
      - OTEL_SERVICE_NAME=api
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=observability
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_DOTNET_EXPERIMENTAL_ASPNETCORE_ENABLE_LOGGING_SIGNAL_INSTRUMENTATION=true
    ports:
      - "5198:5198"
    depends_on:
      - alloy
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./config/alloy-config.alloy:/etc/alloy/config.alloy
    command: 
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
    ports:
      - "4317:4317" #grpc
      - "4318:4318" #http  
      - "12345:12345" #alloy ui
    depends_on:
      - loki
      - tempo
  loki:
    image: grafana/loki:3.4.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - "./config/loki-config.yaml:/etc/loki/config.yaml"
    command: -config.file=/etc/loki/config.yaml

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-config.file=/etc/tempo/tempo-config.yaml"]
    volumes:
      - ./config/tempo-config.yaml:/etc/tempo/tempo-config.yaml
      - tempo_data:/var/tempo
    ports:
      - "3200:3200"
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana:/etc/grafana/provisioning
volumes:
  loki-data:
  tempo_data: {}